# Generated by Django 6.0.4 on 2026-04-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('BRINCO', 'Brinco'), ('COLAR', 'Colar'), ('PULSEIRA', 'Pulseira'), ('ANEL', 'Anel')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade', models.IntegerField()),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível')], max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
